#!/bin/bash
set -eu -o pipefail

if [ $# -ne 1 ]
then
  echo "$0 </out/dir>" >&2
  exit 2
fi

OUT="$1"
shift 1
mkdir -p "$OUT"
OUT=$(readlink -e "$OUT")

APP_DIR=$(dirname "$(readlink -e "$0")")
cd "$APP_DIR"

for f in \
.gitignore \
LICENSE \
Makefile \
README.md \
common.tex \
info.tex \
main.tex \
cpp/.gitignore \
cpp/Makefile \
cpp/config.mk \
dia/.gitignore \
dia/Makefile \
dot/.gitignore \
dot/Makefile \
gnuplot/.gitignore \
gnuplot/Makefile \
pic/.gitignore \
plantuml/.gitignore \
plantuml/Makefile \
qr/.gitignore \
qr/Makefile \
sdk/Dockerfile \
svg/.gitignore \
svg/Makefile
do
  DIR=$OUT/$(dirname "$f")
  mkdir -p "$DIR"
  cp -v "$f" "$DIR/"
done

cd "$OUT"
touch cpp/FOOTER.inl
touch cpp/HEADER.inl
touch slides.tex
