#!/bin/bash
shopt -s nullglob

while sleep 1
do
  inotifywait \
    cpp/*.hpp cpp \
    dia/*.dia dia \
    dot/*.diag dot \
    gnuplot/*.{gpl,dat} gnuplot \
    pic/* pic \
    plantuml/*.plantuml plantuml \
    qr/*.txt qr \
    svg/*.svg svg \
    *.tex

  sleep 0.2
  clear
  time docker run \
             -it \
             --rm \
             -v "$PWD:/mnt/beamer" \
             -w /mnt/beamer \
             -u 1000:1000 \
             baszerr/beamer_cpp \
               make "-j$(nproc)" fast
done
