#!/bin/bash
shopt -s nullglob

APP_NAME=$(basename "$(readlink -e "$0")")
SDK="${APP_NAME}_sdk"
time docker build -t "$SDK" sdk/ || exit $?

while sleep 1
do
  inotifywait \
    cpp/*.hpp cpp \
    dia/*.dia dia \
    dot/*.diag dot \
    gnuplot/*.{gpl,dat} gnuplot \
    pic/* pic \
    plantuml/*.plantuml plantuml \
    qr/*.txt qr \
    svg/*.svg svg \
    json/*.json json \
    *.bib \
    *.tex

  sync
  sleep 0.2
  clear
  time docker run \
             -it \
             --rm \
             -v "$PWD:/mnt/beamer" \
             -w /mnt/beamer \
             -u 1000:1000 \
             "$SDK" \
               make "-j$(nproc)" # fast
done
