#!/bin/bash
set -eu -o pipefail

APP_DIR=$(dirname "$(readlink -e "$0")")
APP=$(basename "$0")

if [ $# -ne 1 ]
then
  echo "$APP </out/dir>" >&2
  exit 2
fi

OUT="$1"
shift 1
mkdir -p "$OUT"
OUT=$(readlink -e "$OUT")


cd "$APP_DIR"
cp -rv \
LICENSE \
README.md \
sdk \
"$OUT/"

cd "template"

for f in \
.gitignore \
Makefile \
common.tex \
info.tex \
main.tex \
cpp/.gitignore \
cpp/Makefile \
cpp/config.mk \
dia/.gitignore \
dia/Makefile \
dot/.gitignore \
dot/Makefile \
gnuplot/.gitignore \
gnuplot/Makefile \
json/.gitignore \
json/Makefile \
pic/.gitignore \
plantuml/.gitignore \
plantuml/Makefile \
qr/.gitignore \
qr/Makefile \
rebuild \
rebuild_on_change \
svg/.gitignore \
svg/Makefile
do
  DIR=$OUT/$(dirname "$f")
  mkdir -p "$DIR"
  cp -v "$f" "$DIR/"
done

cd "$OUT"
touch cpp/FOOTER.inl
touch cpp/HEADER.inl
touch slides.tex
